### ISSUE TITLE
G2 Reverb Randomly Goes Black

### ISSUE THREAD

**Issue by jesseraab** [Kevga/BeatSaberCinema#19]
Thank you so much for your amazing mod; I've used it and loved it for a while. I realize this issue is for a rarely used headset, and therefore quite an edge case, but any attention would be greatly appreciated.

Since I got my HP G2 Reverb I've noticed certain songs at specific but arbitrary places will cause first the left eye to go black, then both eyes, then vision will return after a few seconds. This always occurs in the same places in the same songs. Some songs don't even have videos associated (downloaded) with them. When I uninstall the cinema mod, this issue disappears. I've noticed this issue with at least 1.4.1 and 1.4.2. I'm using a GTX 1080Ti on an i7-2600k with 32g ram. Let me know if this issue is worth investigating and if I can give any more information or log files or anything.

Thanks again for all your hard work!

**Comment by Kevga** [comment]
That's highly unusual. The screens going black sounds like a pretty low-level issue, like the VR runtime or graphics driver. It's also weird that it happens in songs without videos, since in that case Cinema doesn't really do anything, especially not in the middle of a level.

Could you provide the following after the issue occurs again:
- BSIPA log at `Beat Saber\Logs\_latest.log`
- The Unity log (`Player.log`) at `%userprofile%\appdata\locallow\Hyperbolic Magnetism\Beat Saber` (you can paste this path into the Windows Explorer address bar)
- One or two examples of levels that reliably cause the issue, ideally one you play with a video and one without

**Comment by jesseraab** [comment]
I'm embarrassed it didn't occur to me to check the issue in general first... I think it's because it only ever happened to me in beat saber after cinema got readded to the modassistant list, so I suspected that first. Turning down the volume as suggested in that thread you linked prevents the blackout from occurring. So apparently it's something related to the headset's power draw over USB 3.0 when the bass is too heavy. Still strange that it doesn't blackout when the cinema mod is removed, and that it occurs on songs without videos when the cinema mod isn't removed. Anyway, if you want to satisfy your curiosity about how cinema might be modifying the audio to be more bass-heavy or whatever I can reply with more data, logs and such, otherwise I'll just take the advice of that thread and lower the volume and wait for a headset firmware update. Thanks again for your attention and detective skills.

**Comment by Kevga** [comment]
Having a video playing in the background does slightly increase power draw on an OLED screen due to higher brightness values on average. I would assume it happening without video playing to be a coincidence and not related to the mod. Maybe you had a lower volume when you tried it without Cinema or something like that.

**Comment by jesseraab** [comment]
Possibly, yeah. Gonna mark this closed. Thanks for the help and the all the work on the mod. Take care.
