### ISSUE TITLE
Site for a simple search/install maps with file cinema-video.json

### ISSUE THREAD

**Issue by KyberPrizrak** [Kevga/BeatSaberCinema#22]
Hello. I created a beatsaver-mirror with rich functionality. Recently, I was asked to add search maps with file cinema-video.json.
I did:
https://bsaber.org/?filter_mods=cinema&count=100
But there were only 53 maps. 
I wanted to know if you are ready to place this link in your README.md? And are you ready to help me import "Pre-Configured Maps"?

**Comment by Kevga** [comment]
Oh, that's very cool. Didn't know about your site yet. Not every map with a Cinema config has Cinema in the suggestions, so it's great that you can filter by the config file. I will definitely add the link to the README.  

The "pre-configured maps" are just a collection of video configs that I created for myself and then bundled with the mod, so they are available to every user as well. The full list of all config files bundled this way is available in this repo here:  
https://raw.githubusercontent.com/Kevga/BeatSaberCinema/master/BeatSaberCinema/Resources/configs.json

The schema is pretty simple, the custom songs all contain the key `levelID` with the format `custom_level_<hash>`. If they don't start with `custom_level_` then they are configs for OST and DLC songs, which you can ignore. If I can help you any further with this, let me know.

**Comment by KyberPrizrak** [comment]
> The "pre-configured maps" are just a collection of video configs that I created for myself and then bundled with the mod, so they are available to every user as well. The full list of all config files bundled this way is available in this repo here:
> https://raw.githubusercontent.com/Kevga/BeatSaberCinema/master/BeatSaberCinema/Resources/configs.json

You also have "/Resources/Cinema.bplist", and I see the discrepancy of data for the following maps: 
bd45 (present in config, not in bplist)
12cfc (not in config, present in bplist)
13069 (not in config, present in bplist)
Where is the correct data?

**Comment by Kevga** [comment]
Good catch on that discrepancy. bd45 was used for an April Fool's joke and was intentionally not included in the playlist. I will probably remove that config in the next release. The other two are configs that were previously included with the mod, but have since been removed. That they are still in the playlist is a bug in the script that creates both of these files. I will fix that to remove them from the playlist as well. Thanks for mentioning that.

In general the `configs.json` file is what counts, since that determines whether or not the mod will show the download button for the video in game. If you need the keys for the maps instead of the hashes, let me know.

**Comment by KyberPrizrak** [comment]
I did autoparse configs.json (once a day).
The search now displays: "Suggestion: Cinema (integrated)" and "Suggestion: Cinema" 
Waiting delete bd45 (to check auto-delete).

**Comment by KyberPrizrak** [comment]
Autoparsing works.

A few of my thoughts:
Too few songs are supported. I think it is very necessary to add a web page where users can add data to a list of pre-configured maps. You need a webform with three fields: map link, youtube link, offset.
If you make auto-compare the sound sequence from the map and from youtube, you can get rid of the need for pre-moderation (and you can remove the "offset" field in the form, since it can be calculated automatically, and much more accurately).

**Comment by Kevga** [comment]
Thank you for your feedback, greatly appreciated.

The main idea is that any user can add a video to any map themselves via the in-game UI, which works quite well and has been a feature since the first release. Including a bunch of videos configured by me was just to make it easier for users to try out the mod. Also, mappers can add a video to their map when before upload it. That said, crowd-sourced video configs have crossed my mind before, but, as you mentioned, the need for moderation makes this difficult to pull off well. Only checking if the audio matches would probably not be enough.

Using audio fingerprinting to determine the offset automatically is something I looked at before, but I had some trouble getting that to work with the library that I tried. Bundling this library in a way that can be distributed via ModAssistant also seemed challenging. Doing this server-side is an interesting idea though.
