### ISSUE TITLE
Preview button not working

### ISSUE THREAD

**Issue by Fusseldieb** [Kevga/BeatSaberCinema#25]
## 1. Bug description
I'm running Beat Saber 1.16.1 (in `-vrmode oculus` mode, if that matters, using my Quest 2 in Link mode) and the Preview button is there, but if I click it nothing happens. The song doesn't play, nor does it make a click sound. It's just like I'm just pointing at it, even when pressing the trigger.
Everything else works. I can adjust the offset (although I can't preview it, rendering this useless), I can download the videos, play them in a map, etc.

## 2. BSIPA log
< When I get home I'll upload it >

**Comment by Kevga** [comment]
The latest release here on GitHub and also the release that is found in ModAssistant both only support the newest version of the game (1.16.2). Any particular reason you are still using 1.16.1? If you don't want to update your game, you will have to manually install the older release of Cinema 1.4.3, found here on GitHub, which is compatible with your version of Beat Saber.

**Comment by Fusseldieb** [comment]
> Any particular reason you are still using 1.16.1? 

Some mods still don't support 1.16.2, so I'll wait.

> If you don't want to update your game, you will have to manually install the older release of Cinema 1.4.3, found here on GitHub, which is compatible with your version of Beat Saber.

Ahh good to know! But still, it's literally the only thing that's broken. 
Maybe you can do a query for .1 or .2, if it isn't too much work?

And also, thank you for this awesome mod.

**Comment by Kevga** [comment]
> But still, it's literally the only thing that's broken.

Exactly, due to some bad luck, Cinema was pretty much the only thing that was broken in the update from 1.16.1 to 1.16.2, because it modifies a part of the game's code that was changed in that update. Mods were marked as compatible for that update to make the update smoother for users, because everything else works on both 1.16.1 and 1.16.2. Very little has changed in that update. 

Backwards compatibility is honestly not worth the effort with how frequently the game updates. Additionally you can just use an older version of the mod. If you want new features, you just have to update the game.

**Comment by Fusseldieb** [comment]
> Exactly, due to some bad luck, Cinema was pretty much the only thing that was broken in the update from 1.16.1 to 1.16.2, because it modifies a part of the game's code that was changed in that update. Mods were marked as compatible for that update to make the update smoother for users, because everything else works on both 1.16.1 and 1.16.2. Very little has changed in that update.

Huh? That's interesting...
So that means that I can update to 1.16.2 and mods like Chroma, Noddle and **ParticleOverdrive** should still work?

That would be amazing by itself...

**Comment by Kevga** [comment]
>So that means that I can update to 1.16.2 and mods like Chroma, Noddle and ParticleOverdrive should still work?

Yes on all of those. 

>That would be amazing by itself...

It's not that surprising. It happens quite regularly that game versions get aliased in ModAssistant because there were no breaking changes. You can't expect every modder to go back to their older GitHub releases and update the description to include the new game version. I assume that's why you linked ParticleOverdrive in particular.

**Comment by Fusseldieb** [comment]
> It's not that surprising. It happens quite regularly that game versions get aliased in ModAssistant because there were no breaking changes. You can't expect every modder to go back to their older GitHub releases and update the description to include the new game version. I assume that's why you linked ParticleOverdrive in particular. Though, Shadnix has indeed updated the description now that I asked to make sure about the compatibility.

Yup, that was my fear, I love all 4 mods including yours. Breaking even one of them would be a no-go for me ahahaha

Thanks you for asking him :)

Will update it today!

Also thanks for your time!
