### ISSUE TITLE
Override environment

### ISSUE THREAD

**Issue by drezack** [Kevga/BeatSaberCinema#27]
When I use screenHeight or screenPosition parameters in the cinema-video.json file, my “Override Default Environment” stops working. Removing these params from the json file brings the correct environment back.

**Comment by Kevga** [comment]
That is intentional, though admittedly poorly documented at the moment. 

Modifying `screenHeight`, `screenPosition` and/or using environment modifications makes the config specific to the environment that was selected by the mapper, since overriding the default means it can no longer be guaranteed that all supported environments look correctly. Linkin Park is one example of an environment that very quickly looked broken when not using the default placement for the video screen. If this leads to an environment being selected that differs from the one you intended to use, you can specify the one you want using the `environmentName` parameter. The internal names of all the environments are listed as `Info.dat Name` [here](https://bsmg.wiki/mapping/basic-lighting.html#environment-previews).
