### ISSUE TITLE
Force turning on after Pause with proper settings.

### ISSUE THREAD

**Issue by AlmostAnthony** [Kevga/BeatSaberCinema#42]
This is something I've observed for a really long time through multiple versions but didn't really see it as an issue until now. This might be a 2 part issue, as this seems to be the case with every base environment other than Big Mirror.

Firstly, if you don't have an environment override set in the cinema json (or even if you do) and you have "Override Big Mirror" set OFF in cinema settings, then when using any other environment, most noticeably Triangle or Nice the video is way in the back behind all environment elements and barely visible, it also seems like it doesn't properly have all the user settings applied (such as transparency).

I have noticed that if you've played around with the cinema settings however and set things like transparency, curvature, border radius, etc., and then set all of Cinema to OFF in it's settings, then if you Play or Practice a song any time you pause and unpause Cinema turns itself on and has all the proper settings you have specified, puts it upfront perfectly viewable, as well as plays the video fresh from the very start at the time of pausing making it off time regardless of the starting offset.

With a current project this is most noticeable because even with the environment override in the cinema config to Nice environment the video seems out of place like it isn't really suppose to be there, and it seems to not have the curvature or transparency set either. But doing the method of turning off Cinema and pausing/unpausing places the video in the perfect placement with all the proper settings, curvature, transparency, etc.. I don't want to manually specify the location and size and such of the video in the config in fear of it being improperly placed for any other environment if overridden by the user. I have provided screenshots of the placement and look of the video both ways, as well as my personal cinema settings.

The look of the video when off through the pausing method is the perfect look that I _would_ like for the cinema video to appear in that environment.

[_latest.log](https://github.com/Kevga/BeatSaberCinema/files/7450702/_latest.log)
![Cinema-Settings1](https://user-images.githubusercontent.com/32372732/139622944-ed00deb9-723f-498a-91ac-6c4441d96f2f.png)
![Cinema-Settings2](https://user-images.githubusercontent.com/32372732/139622947-dc6a4df8-cb0a-4d01-81dd-eb93f022500d.png)
Below is Nice Environment with Cinema ON
![Cinema_ON_NiceEnv](https://user-images.githubusercontent.com/32372732/139622247-68294de0-e1de-4dda-837c-bce2a57e8ea6.png)
Below is Nice Environment with Cinema OFF after pausing & unpausing
![Cinema_OFF_NiceEnv](https://user-images.githubusercontent.com/32372732/139622424-b52d946c-6f20-4cbb-b4f5-f6d3b2ebf0be.png)

**Comment by Kevga** [comment]
If Cinema is disabled, the video should of course not suddenly start playing after resuming a paused map. That's a bug that I will fix.  

As you noted, some environments don't look good if you just add the video screen in. In fact most environments require slight tweaks to make the video screen fit in nicely, and I modified quite a few environments for that reason. There's a list of all supported environments in the readme. Some environments would require tweaks that are large enough to make those environments lose their identity, which is why I don't support every environment. The Big Mirror override setting simply loads the Big Mirror environment if an environment that is not supported was selected (either by the mapper or by the player), so that you can use Cinema for any map without issues and without having to think about any of this.  

> I don't want to manually specify the location and size and such of the video in the config in fear of it being improperly placed for any other environment if overridden by the user.

If a mapper wants to use Cinema on an environment that is not in the list of supported environments, they can modify that environment themselves to make it work. If there are either environment modifications or a custom screen position in the video config, the Big Mirror override will be disabled, and additionally the player also loses the ability to override a different environment for that map. The reason for that is precisely what you mentioned: The screen placement is specific to the environment and may not work on other environments.

Regarding your specific example: What happens is that the video screen stays at the location where it is placed while in the menu scene, since video playback is disabled and therefore doesn't initialize with the proper placement and map settings after loading the map. If you want the screen at the location of the second screenshot, you can use the menu placement in your config:
`"screenHeight": 8.0, "screenPosition": {"x": 0, "y": 4, "z": 16}`
Note that a distance of 16 meters is very close though and might impact playability. The default distance (the one in the first screenshot) is 67.8 meters. The rings in the Nice environment are hard to deal with, which is why I didn't add this environment to the list of supported environments.
