### ISSUE TITLE
Cinema video's not installing

### ISSUE THREAD

**Issue by Takeout55** [Kevga/BeatSaberCinema#68]
This is the log, my issue is the fact that when installing a video onto a map the download always reaches 15% before giving me an error message. I use BSmanager to install my mods
I am unable to find what the issue is
[_latest.log](https://github.com/Kevga/BeatSaberCinema/files/12388102/_latest.log)

**Comment by Kevga** [comment]
YouTube recently made a breaking change that requires an update of yt-dlp. Beat Saber versions 1.29 and 1.31 have an updated version available.

Since you are using 1.28, you either have to update your game, or manually install the updated yt-dlp. You can download it from beatmods.com or from the yt-dlp GitHub releases.
