### ISSUE TITLE
No video configuration when choosing a song from a playlist

### ISSUE THREAD

**Issue by Noahffiliation** [Kevga/BeatSaberCinema#7]
When choosing a song from a custom playlist, it shows that I have no video configuration, even though I have the appropriate .json and .mp4 files for each song. However, when choosing songs from the 'Custom Songs' or 'Favorites' tabs, it loads all of the video configurations.

**Comment by Kevga** [comment]
Thanks for reporting this. 

The issue here is that levels selected via PlaylistManager have a different data type than when selected from the built-in menus, which makes Cinema look for their folder path in the wrong location.

I talked with the developer of PlaylistManager about it and it looks like this might get fixed in the future. For the meantime I added a workaround in Cinema to address this.

**Comment by Kevga** [comment]
The corresponding issue at the PlaylistManager repo can be found here:
https://github.com/rithik-b/PlaylistManager/issues/5

I will most likely revert commit 508dc19 after a fixed build of PlaylistManager is released to get rid of the reference to BeatSaberPlaylistsLib.
