### ISSUE TITLE
[Feature Request] Support environment override with Chroma mod

### ISSUE THREAD

**Issue by nanikit** [Kevga/BeatSaberCinema#72]
## Background

I tried overriding [this map](https://beatsaver.com/maps/2efde)'s environment, but I couldn't.

## Steps to reproduce

1. Beat saber version: 1.29.1
2. Install Cinema, Chroma mod.
3. Download [chroma beatmap](https://beatsaver.com/maps/2efde).
3. Add `cinema-video.json` as follows.
```json
{
  "videoID": "lso3jgaWRJg",
  "title": "[한글자막] P丸様- MOTTAI(아까워)",
  "author": "[니와]",
  "videoFile": "[한글자막] P丸様- MOTTAI(아까워).mp4",
  "duration": 163,
  "offset": 160,
  "environmentName": "BigMirrorEnvironment"
}
```
4. Play the beatmap.

## Expected behavior

Big Mirror environment should appear.

## Actual behavior

Timbaland environment appears.

## Additional context

When I disable Chroma, environment is changed well.

**Comment by Kevga** [comment]
Cinema intentionally applies its environment override earlier than Chroma, since lots of Chroma maps are specifically made for a certain environment. So if Chroma also forces the map to use a certain environment, it will override Cinema's environment choice. This also makes it more convenient for mappers that want to use both plugins for their map, since they can use an environment that is not supported by Cinema and use Chroma to make space for the video screen without also having to configure that environment choice in the video config. Additionally, this way the map still plays fine if the player only has Cinema and not Chroma installed, since in that case Cinema will override to an environment that is supported.

Sorry for the very late reply.
