### ISSUE TITLE
[Feature Request] Cinema for Quest

### ISSUE THREAD

**Issue by Fusseldieb** [Kevga/BeatSaberCinema#74]
## Quick summary
I would like to have the Quest supported. Back then the Quest 2 hardware barely kept up with modded Beat Saber, but now that we have the Quest 3, new possibilities open up.
I would really love this!

## Details
The existing mod, adapted for the Quest

**Comment by Kevga** [comment]
The Quest port is being worked on at https://github.com/kodenamekrak/Cinema

**Comment by Goldenfreddy0703** [comment]
Hey there sorry to bother but is the Quest port for this still being worked on? I would love to utilize the Cinema Mod for Quest. I was trying to figure out a way to build it or make it a qmod file for bsquest but i got stuck unfortunately.

**Comment by AdLf0208** [comment]
> Hey there sorry to bother but is the Quest port for this still being worked on? I would love to utilize the Cinema Mod for Quest. I was trying to figure out a way to build it or make it a qmod file for bsquest but i got stuck unfortunately.

same here... I successfully built the project using qpm and even got needed libcinema.so library and all dependencies but no luck, no matter what i did, it's not shown in the game, even though quest patcher successfully identifies the library and loaded the corresponding .so dependencies. I think it's just not compatible with my 1.37 version of the game since manifest clearly shows 1.40,,,,, Shame there's no .qmod build already I just think the guy who forked the project just skipped the release, maybe I need to change branch to last mentioning of 1.37 and compile from there...
